# MkDocs configuration for Netlify builds

INHERIT: mkdocs-base.yml
site_url: "https://docs.percona.com/proxysql"

theme:
  name: material
  custom_dir: _resource/overrides

#Google Analytics configuration 
extra:
  analytics:
    provider: google
    property: G-J4J70BNH0G
